add types to pretty much everything
tsc is still producing a handful of errors:

src/blockfall.ts(49,12): error TS2511: Cannot create an instance of the abstract class 'Game'.
src/blockfall.ts(77,21): error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
src/blockfall.ts(90,16): error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
src/blockfall.ts(100,14): error TS7017: Index signature of object type implicitly has an 'any' type.
src/blockfall.ts(361,43): error TS2322: Type 'number' is not assignable to type 'number[]'.
src/blockfall.ts(362,23): error TS2345: Argument of type 'number[][]' is not assignable to parameter of type 'number[]'.
  Type 'number[]' is not assignable to type 'number'.